-- MySQL Script generated by MySQL Workbench
-- Sun Sep 26 13:23:52 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema MusicBands2
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema MusicBands2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `MusicBands2` DEFAULT CHARACTER SET utf8 ;
USE `MusicBands2` ;

-- -----------------------------------------------------
-- Table `MusicBands2`.`AllBands2`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MusicBands2`.`AllBands2` (
  `idAllBands2` INT NOT NULL AUTO_INCREMENT,
  `GroupName` VARCHAR(60) NOT NULL,
  `GroupMembers` VARCHAR(200) NOT NULL,
  `Genre` VARCHAR(45) NOT NULL,
  `Startyear` INT NOT NULL,
  `#Hitparade` VARCHAR(45) NOT NULL,
  `Concerts` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idAllBands2`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MusicBands2`.`TopChart2`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MusicBands2`.`TopChart2` (
  `idTopChart2` INT NOT NULL AUTO_INCREMENT,
  `idAllBands2` INT NOT NULL,
  `GroupNameT` VARCHAR(50) NOT NULL,
  `GroupMembersT` VARCHAR(200) NOT NULL,
  `Genre` VARCHAR(45) NOT NULL,
  `StartyearT` INT NOT NULL,
  `HitparadeT` VARCHAR(45) NOT NULL,
  `Concerts` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTopChart2`),
  INDEX `AllBands_idx` (`idAllBands2` ASC) VISIBLE,
  CONSTRAINT `AllBands2`
    FOREIGN KEY (`idAllBands2`)
    REFERENCES `MusicBands2`.`AllBands2` (`idAllBands2`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MusicBands2`.`City2`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MusicBands2`.`City2` (
  `idCity2` VARCHAR(300) NOT NULL,
  `City` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCity2`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MusicBands2`.`Concerts2`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MusicBands2`.`Concerts2` (
  `idConcerts2` INT NOT NULL AUTO_INCREMENT,
  `idAllBands2` INT NOT NULL,
  `idCity` VARCHAR(300) NOT NULL,
  `Country` VARCHAR(45) NOT NULL,
  `Date` DATE NOT NULL,
  PRIMARY KEY (`idConcerts2`),
  INDEX `AllBands_idx` (`idAllBands2` ASC) VISIBLE,
  INDEX `City_idx` (`idCity` ASC) VISIBLE,
  CONSTRAINT `AllBands`
    FOREIGN KEY (`idAllBands2`)
    REFERENCES `MusicBands2`.`AllBands2` (`idAllBands2`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `City`
    FOREIGN KEY (`idCity`)
    REFERENCES `MusicBands2`.`City2` (`idCity2`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
